### ISSUE TITLE
Gym details not updated correctly

### ISSUE THREAD

**Issue by Glennmen** [RocketMap/RocketMap#2071] opened 2017-05-29 19:56 UTC
## Expected Behavior

Show the correct pokemon + trainers in gym when you are viewing the gym details (sidebar).

## Current Behavior

Updates the gym color but doesn't update the pokemon + trainers in gym correctly.
Sometimes still shows old trainers in new gym or not showing all of the trainers that should be in the gym.

Gym scanned with RM
![RM gym](https://image.prntscr.com/image/b4c041cebf5444f1be064766ee98925f.png)

Gym scanned with 3rd party scanner
![3rd party gym](https://image.prntscr.com/image/a1cb7905a0854e788af9297597cf18dc.png)

In the provided image you can see that the RM gym is missing a trainer/pokemon even though it has recently been scanned.

**Comment by SwenWacker** [comment] 2017-05-31 07:15
I can confirm this behavior (gym only instance; pure, fresh RM)

**Comment by jorgitoh** [comment] 2017-06-06 15:18
I can confirm the same:

Last_scanned = 5min ago
Last_modified = 1 day ago

I check with gymhuntr or game client and the pokemons are differents.

**Comment by Glennmen** [comment] 2017-06-06 15:54
@SwenWacker @jorgitoh I haven't tested it yet but this PR might solve this gym issue: #2075

**Comment by jorgitoh** [comment] 2017-06-10 11:35
@Glennmen same error with #2075. Last scanned 1 sec ago, last modified 8 hours ago. Maybe because the gym have 52k all the time but the members change?

**Comment by friscoMad** [comment] 2017-07-06 06:06
I hope this has been fixed with the latests changes after the gym update. Could you confirm?

**Comment by Glennmen** [comment] 2017-07-06 07:39
@friscoMad not running RM anymore, maybe one of the other can check.
@SwenWacker @jorgitoh

**Comment by SwenWacker** [comment] 2017-07-06 10:45
None of my community has talk about this since Gyms has changed. Close.

**Closed** 2017-07-29 12:37 UTC
