### ISSUE TITLE
[IDEA] Possible Solution to Account-Jumping in Hex Scans?

### ISSUE THREAD

**Issue by kevdotcom** [RocketMap/RocketMap#1557] opened 2016-11-18 05:00 UTC
So... We are having problems because accounts always have to "jump" ahead of the other ones while doing a hex scan with multiple accounts, right?

What if we would start the first account in the middle, let it scan a set amount of circles (steps), then start the 2nd account also in the middle, let it scan, then the 3rd account and so on... (see image below)

We could even start the accounts ahead of each other to avoid waiting at the beginning.

If we could scan like that, our accounts would always only go one step and wouldn't ever jump.

The distance between the accounts could be either user-defined or the number of scan-circles divided by the number of accounts used.

Unfortunately, I don't know how to put this in code, so I hope someone else might find this idea useful and can maybe make a PR out of it ;)

![image](http://i.imgur.com/ebG42r9.png)

**Comment by baskettcase** [comment] 2016-11-18 05:06
Ugh, I thought this was how it was done already.. yes I think this would be a whole lot better, although no solution that I can think of would be perfect depending on the number of accounts you are using. If you have 10 accounts then when the first account starts scanning again, it will most likely be a decent ways away from the first scans it did... add 20 accounts, etc, that distance is potentially greater (depending on where it stops). Anyways.. I would like this to be the default method!

**Comment by kevdotcom** [comment] 2016-11-18 05:11
@baskettcase - The path is already like that, but currently the accounts constantly jump ahead of each other because the next circle just gets assigned to the account thats coming off the scan delay first.

**Comment by sLoPPydrive** [comment] 2016-11-18 05:19
This exact idea was tried before in a super experimental branch but never got finished. I agree this would be the optimal hex scan scheduler but it doesn't seem to be that easy to implement. The cause is most probably that the scheduler has to keep the accounts equidistant no matter what. Some accounts might take longer than others for scanning so they would fall behind. You would have to detect this and add delays for all other accounts. Not trivial but definitively possible.

**Comment by stefanvds1** [comment] 2016-11-18 06:46
@sLoPPydrive the SD could start from the moment the scan starts. any delays encountered during scanning are therefore ignored. hence no need to delay the rest of the queue.
the only problem here is that an st13 and sd150 would take forever to do a full scan. so rather than doing it the suggested way, that they all start at position 1, they can all start somewhere along the path of the full hex. 

for example, if you have as many accounts as there are 'hops/scans' in the hex, each would be put somewhere in the hex to immediately cover the whole scan. then after the SD expires, they each move one step forward, and so on, and so on.

if you have half the amount of accounts, divide the amount of 'hops/scan's by the number of accounts, and place them on the starting grid so that they each have an equal amount of space in between them. for half the amount of accounts the whole hex would be scanned every two 'hops'. no more jumping.

this also would work with skip-empty as each account simply moves on to the next location. sure, with skip empty you will still have some jumping, but it will be way less than the random jumping mess you get now.

weather or not this makes any difference at all for triggering captcha's... it's a guessing game.

**Comment by WalterMagnum** [comment] 2016-11-18 13:03
You can do this already, but not gracefully.  If you are using a batch to startup, just run multiple instances of runserver.py in the same location with different accounts and set the appropriate pause between running them.

**Comment by faketits** [comment] 2016-11-18 13:31
this idea is good for scan jumping as well. I let my friends scan for different locations with 5acc each server -st 2, if i use -st 3 the 5 accounts scan step by step and each account scan far location(5 steps away from last step scanned on that specific user) and therefor some of the scans get 0. your idea can reduce the amount of 0's scans...

**Comment by arivero** [comment] 2016-11-18 16:26
Batch startup is not the answer, it eats a lot of memory and well, it is not gracefully, nor being able to look for collisions even in the future (well, perhaps pivoting on the database)

Main implementation problem is that the scheduler passes a queue to the workers, that can only take jobs from the head of it.

It could be promoted to a https://docs.python.org/2/library/heapq.html heapq or similar structure, each point with an index number, and each worker asking for the next task to the one it has done. But then some other changes should be needed to the process of refilling the queue, so that when a worker reaches the end of it, a refill is one. Perhaps the whole mechanism needs to be substituted :-(

**Comment by Janglinator** [comment] 2016-11-18 21:10
This suggestion has been brought up a ridiculous amount of times.

Here's the problem:  this assumes that the workers work at the exact same pace, which is FAR from being the truth.  So either you'll have workers scanning on top of each other (because the front one fell behind), thus leaving large not-recently scanned gaps, or else you'll need to hold back your faster accounts to accommodate for the slower ones.  Either route, you destroy efficiency.

I might recommend checking out PR #1367

**Comment by baskettcase** [comment] 2016-11-18 21:19
If each worker has a set number of cells to do in a certain spot, then why does it matter if they finish at the same time or not? and it seems trivial to make sure that they don't scan the same area. Make an array that follows the same path that it does currently, assign the first 1/5th to worker 1, the 2nd 5th to worker 2, up to worker 5, or however many workers there are.

**Comment by Janglinator** [comment] 2016-11-18 21:24
@baskettcase That's not what he was suggesting, but I understand what you mean; just have some workers do a few scans, then jump back to where it started.  But anytime I say the word "jump", assume "ban".  We can't jump.  Ever.  That's what my PR attempts to solve.  No jumps, workers work in a confined space, and are responsible for scanning only that area.

**Comment by simonbuehler** [comment] 2016-11-18 21:31
actually you can jump -  but you have to wait so that the speed limit doesn't hit , which makes it slow again

**Comment by Janglinator** [comment] 2016-11-18 21:35
Why not just not jump?  You're suggesting a solution that significantly less that optimal efficiency, and for what gain?

**Comment by baskettcase** [comment] 2016-11-18 21:36
From the OP I think he's saying what I was saying. Unless you guys are referring to what someone else said...? the OP just didn't draw out the entire path for one worker, two workers, etc, he just simplified it, but the first photo would be the one worker doing all of it. The 2 worker scenario, would be split the path exactly in half (in the exact same path it would normally take), have the 1st worker start at the beginning and the 2nd worker start halfway through the path at the same time. Then 3 worker scenario, same, etc etc.. So pretty much what I said previously.

**Comment by Janglinator** [comment] 2016-11-18 21:51
@baskettcase That's not what OP said.   "What if we would start the first account in the middle, let it scan a set amount of circles (steps), then start the 2nd account also in the middle"

**Comment by baskettcase** [comment] 2016-11-18 22:00
Ah ok thanks @Janglinator I thought he was just saying it in an unclear method, maybe I read into it what I wanted to hear :)

**Comment by musicgreg** [comment] 2016-11-18 22:23
What if the entire area was split into an amount of smaller areas equal to the number of workers, and then each worker scanned their own designated area in a pattern that does not require jumping (picks up where it started)?  Then you wouldn't have to worry about jumping and you wouldn't have to worry about overlap.

**Comment by SonOfStone** [comment] 2016-11-18 22:30
Beehive scans limiting workers to a certain area has already been implemented in PR #1367. It works well you just have to cut and paste the code yourself. In addition to this I also use PR #1476 which calculates the speed of the workers and makes sure they stay under the speed limit.

**Comment by Janglinator** [comment] 2016-11-18 22:39
@SonOfStone You might like this branch  :)  https://github.com/Janglinator/PokemonGo-Map/tree/all_supported_prs

It's a (hopefully) temporary merge of latest of dev with PRs 1367, 1539, 1476, and 1556.  I'm sad to say it was even necessary to make, I'm hoping these great PRs will get some attention soon.

**Comment by kevdotcom** [comment] 2016-11-18 23:35
@Janglinator I mean exactly what baskettcase said... All workers go the full path and chase each other.

"let it scan a set amount of circles" was probably unclear.

**Comment by Janglinator** [comment] 2016-11-20 02:56
@kevdotcom I know that's what you meant  :)  But that's not what baskett meant.

You meant: workers scan the *full* path, but chase eachother around it.

Quote from you: "What if we would start the first account in the middle, let it scan a set amount of circles (steps), then start the 2nd account also in the middle..."

@baskettcase meant: workers scan only *part* of the full path (1/n of the full path, where n is the number of workers), then have that worker go back to where it started (not necessarily the beginning of the full path)

Quotes from baskett:  "...assign the first 1/5th to worker 1, the 2nd 5th to worker 2, up to worker 5, or however many workers there are."
"The 2 worker scenario, would be split the path exactly in half (in the exact same path it would normally take), have the 1st worker start at the beginning and the 2nd worker start halfway through the path at the same time."

**Comment by ultrafunkamsterdam** [comment] 2016-11-22 19:44
in search.py
`-    delay = args.accounts.index(account) + ((random.random() - .5) / 2)
+    delay = args.accounts.index(account) * 10 + ((random.random() - .5) / 2) ## Higher login delay per account so no multiple accounts scanning same location`

**Comment by urinella** [comment] 2016-11-28 22:24
Any news here?
This would be a very big advantage for scanning with speedlimit. So the workers don't have to wait too long

**Comment by ultrafunkamsterdam** [comment] 2016-11-29 07:38
^^ see my answer. It works for me, so let's test it.

**Comment by urinella** [comment] 2016-11-29 13:18
@ultrafunkamsterdam 
Thanks for the hint. Not working for me like expected.

I thought one account starts and after a while other accounts follow the same path. 
Still teleporting one after one. Maybe issue with my activates PRs

**Comment by sebastienvercammen** [comment] 2017-07-17 00:47
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).

**Closed by sebastienvercammen** 2017-07-17 00:47 UTC
