### ISSUE TITLE
pokemon respawning same location after despawn. (false detection)

### ISSUE THREAD

**Issue by boby360** [RocketMap/RocketMap#1558] opened 2016-11-18 08:16 UTC
## Expected Behavior
expect there to not be false detection of pokemon.

## Current Behavior
Pokemon show up as a new scanned pokemon with countdown. However they aren't at the location ingame. Doesnt happen often. although i noticed it spesifically with rare pokemon.

## Possible Solution
![untitled](https://cloud.githubusercontent.com/assets/1607258/20423220/ff4b98a4-ad23-11e6-8e56-b42c6d546c88.png)

## Steps to Reproduce (for bugs)

1.
2.
3.

4.

## Your Environment

* Version used: commit 1065 
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile):
Windows XP

**Comment by springjools** [comment] 2016-11-18 09:15
Is this spam? I don't understand what the possible solution means, please explain better.

**Comment by kevdotcom** [comment] 2016-11-18 14:23
The possible solution is errors?

**Comment by Holzberg** [comment] 2016-11-18 19:49
I have the same issue and it also triggers extra notifications.

There have been reports that pokemon are now spawning from 30-60 minutes.  I witnessed this last night when my map said the Muk was supposed to be gone, but it was still there.

I think what happens is the map expires the pokemon after 15 minutes, but then scans it again and assigns it another 15 minutes.  I'm not sure if it has been 100% confirmed that the pokemon spawning longer is permanent or exactly what the amount of time is.

**Comment by boby360** [comment] 2016-11-19 00:09
Sorry I'm a Github scrub. But yeah was holzberg said. For me I ran out. Caught a kabuto. Then did some shit. Noticed there was one in the same spot with 10min. Thought it was weird to be in the exact same spot. But anywho I went there. Sat for 2min and was guaranteed in the range. Didn't show up. Happened for 3 rare Pokemon and got home. Noticed this occasional error. So figured I'd try and post to get a fix.

**Comment by boby360** [comment] 2016-11-19 00:16
@kevdotcom fixing the error is the solution. Atleast my guess.  ;)

**Comment by simonbuehler** [comment] 2016-11-28 13:58
there are also spawns that hide the _same_ pokemon for some time and then reveal it again during one hour, once caught (or fleed) it won't reappear for you but might on the map

check details: https://www.reddit.com/r/pokemongodev/comments/4yzqc2/spawn_point_types_clearing_confusion/
duplicate to #937

**Comment by chromer90** [comment] 2016-11-28 23:24
In my opinion this most likely means your spawn times are wrong. I had the same issue or so I though until I started using the PR with the time fix. Now instead of spawning for 15 minutes and reappearing it spawns for 30 minutes or more and seems to be accurate. I had a growlithe I know spawned for over 40 minutes because I missed it when it initially went off but drove by later and it was still there. The only way to test this would be for you to encounter a pokemon and then see it respawn again and have someone else try to encounter it and see if they see it. If they can see it and you can't that means it is the same exact pokemon.

**Comment by sebastienvercammen** [comment] 2017-07-17 00:47
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).

**Closed by sebastienvercammen** 2017-07-17 00:47 UTC
