### ISSUE TITLE
Map are not showing Pokemons from Lured Pokestops

### ISSUE THREAD

**Issue by elrosti** [RocketMap/RocketMap#715] opened 2016-08-15 20:04 UTC
Map are not showing Pokemons from Lured Pokestops
## Expected Behavior

The pokemon should be available in the map
## Current Behavior

The pokemon is not show in the map
## Your Environment

Ubuntu 16.04, Python 2.7

(Sorry for my bad English, is not my native language)

**Comment by Shobba** [comment] 2016-08-15 20:17
Check Pull Request #555, there's a discussion about what changed about the pokestop API and why it's difficult right now to show correct lure data. Perhaps it gives you a bit of an insight into what's going on right now.

**Comment by BaIthamel** [comment] 2016-08-16 07:53
I'm not sure utils.py is the place for this.

**Comment by Zoruk** [comment] 2016-08-16 11:56
Whis this commit the lured pokemon are displayed but it's a dirty trick https://github.com/Zoruk/PokemonGo-Map/commit/c95f4ac68af4a7ed969cc5d04c891f398b80165b

**Comment by SirPownzalot** [comment] 2016-08-16 19:30
@Zoruk Is that commit that you linked already in the new dev version? If not, could you give a quick guide on how to input that fix in my files? Kind of a noob at this ._.

**Comment by SirPownzalot** [comment] 2016-08-16 20:23
Would you mind lending me a hand? How do I add these changed to my files? I know this is not the proper channel for this sort of help, but I'm in the Discord channel if you feel like helping ._.

**Comment by SkOODaT** [comment] 2016-08-16 21:47
i literally just threw his changes in and used the updated pogoAPI here on pokemon map they forked and i see lured pokes perfect now just need to readd lured infos in it was all removed :( but lured pokes are better then none lol

**Comment by Zoruk** [comment] 2016-08-17 13:56
https://github.com/PokemonGoMap/PokemonGo-Map/pull/768

**Comment by sebastienvercammen** [comment] 2017-02-23 13:08
Closing because the issue is much older than the current codebase. If your issue still persists, please make a new issue and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:08 UTC
