### ISSUE TITLE
Cordinates move after being parsed

### ISSUE THREAD

**Issue by delro92** [RocketMap/RocketMap#767] opened 2016-08-17 09:42 UTC
## Expected Behavior

Perfectly aligned coordinates should stay perfectly aligned.
## Current Behavior

All coordinates move around slightly 
## Steps to Reproduce (for bugs)
1. Generate beehive with location_generator.py
2. Check that all locations are aligned
3. Load them and start the workers
4. Open the map and see how the beehive is scrambled
## Your Environment

- Version used: https://github.com/PokemonGoMap/PokemonGo-Map/commit/7cdb8c1ec3af5eda258dadc9f8c6f2095988f202
- Operating System and version (desktop or mobile): Debian

Here is the worker log where the locations get parsed and switched:

> `2016-08-17 09:25:42,214 [      MainThread][     utilities][    INFO] Location for '-34.6252343212, -58.3665116285
> ' found: Azopardo 1502-1504, C1107AEB CABA, Argentina
> 2016-08-17 09:25:42,215 [      MainThread][     utilities][    INFO] Coordinates (lat/long/alt) for location: -34.6252379 -58.3665431 0.0
> 2016-08-17 09:25:42,808 [      MainThread][     runserver][    INFO] Parsed location is: -34.6252/-58.3665/10.6848 (lat/lng/alt)`
## Screenshot (please ignore the missing scanned zones, I had just restarted the server)

Check how the overlaps are not neat at all: https://i.imgur.com/FjuXddc.png

**Comment by chuyskywalker** [comment] 2016-08-18 06:49
`285 ' ` Get rid of the extra space.

**Comment by Xcelled** [comment] 2016-08-18 08:04
@chuyskywalker why are we not trimming that?

**Comment by chuyskywalker** [comment] 2016-08-18 13:57
^shrug^ cause we didn't think to.

**Comment by sebastienvercammen** [comment] 2017-02-23 13:08
Closing because the issue is much older than the current codebase. If your issue still persists, please make a new issue and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:08 UTC
Labels: backend, bug
