### ISSUE TITLE
[Bug] mysqld: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by billbo99** [RocketMap/RocketMap#322] opened 2016-08-09 17:25 UTC
## Current Behavior

syslog on database server is generating 100's of 
`mysqld: Deadlock found when trying to get lock; try restarting transaction`

And there are several of these error messages popping up
`Aborted connection 38 to db: 'pokemongomapdb' user: 'xxx' host: 'ubuntu' (Got an error reading communication packets)`
## Possible Solution

1) Change the workers to send their collected data via restapi to the db server process, which then performs batch inserts into the database.

2) Have each thread insert there data into a queue on the worker, then have a dedicate thread insert the data into the database in batches of 100 as the queue fills up.
## Steps to Reproduce (for bugs)

Running a beehive with
   steps = 8
   leaps = 3
   accounts per worker = 8  (296 accounts total)
## Your Environment

VM ware guests all running  Ubuntu 16.04.1 server
3g memory for main db server
2g memory for 4x worker servers
37 worker processes spread out over the worker servers.
## Fixes I have tried

Pinned mysql into memory to speed things up.
Set max connections to 5000 just to be sure.
Dropped and re-created the mysql database to force indexes to be recreated.

**Comment by invisiblek** [comment] 2016-08-09 18:23
Get me a full log please

**Comment by billbo99** [comment] 2016-08-09 20:25
Attached are 10x logs from my workers.
[W1.tar.gz](https://github.com/PokemonGoMap/PokemonGo-Map/files/409792/W1.tar.gz)

I have now turned off pokestops and gyms from being collected .. that seems to have reduced deadlock issues greatly. 

Looking at the code,  the deadlock errors maybe a false positive as the inserts are being rerun successfully,  but by using a dedicate thread to manage the bulk inserts reduces the likely hood even further.

If/When PR https://github.com/PokemonGoMap/PokemonGo-Map/pull/161 get merged I can run a separate worker process to scan just for stop's and gym's with a larger scan-delay to pick up the lured pokemon.

**Comment by totoberg123** [comment] 2016-08-12 19:06
Same problem.

**Comment by rrbailey89** [comment] 2016-08-13 16:45
I also get this error pretty often.

```
2016-08-13 09:44:27,062 [ search_worker_0][        models][ WARNING] (1213, u'Deadlock found when trying to get lock; try restarting transaction')... Retrying
2016-08-13 09:44:27,249 [ search_worker_0][        models][    INFO] Upserted 2 pokemon, 16 pokestops, and 6 gyms
2016-08-13 09:44:31,696 [ search_worker_1][        search][    INFO] Search step 7 beginning (queue size is 54)
2016-08-13 09:44:32,170 [ search_worker_1][        models][    INFO] Upserted 0 pokemon, 15 pokestops, and 5 gyms
2016-08-13 09:44:36,697 [ search_worker_0][        search][    INFO] Search step 8 beginning (queue size is 53)
2016-08-13 09:44:37,345 [ search_worker_0][        models][    INFO] Upserted 1 pokemon, 14 pokestops, and 5 gyms
2016-08-13 09:44:41,697 [ search_worker_1][        search][    INFO] Search step 9 beginning (queue size is 52)
2016-08-13 09:44:42,154 [ search_worker_1][        models][ WARNING] (1213, u'Deadlock found when trying to get lock; try restarting transaction')... Retrying
2016-08-13 09:44:42,338 [ search_worker_1][        models][ WARNING] (1213, u'Deadlock found when trying to get lock; try restarting transaction')... Retrying
```

**Comment by CtrlAltDefeat94** [comment] 2016-08-14 19:14
I was running fine with 56 accounts (2x -lp 2) and out of nowhere i'm starting to get them too.

**Comment by brettgus** [comment] 2016-08-15 06:04
Same here, getting them too since updating

**Comment by totoberg123** [comment] 2016-08-15 11:39
First the Deadlock error, and after some time i get this:
http://prntscr.com/c5xq52/direct

**Comment by Okumba** [comment] 2016-08-16 12:32
Getting this alot too:
2016-08-16 09:23:00,053 [ search_worker_0][        models][ WARNING] (1213, u'Deadlock found when trying to get lock; try restarting transaction')... Retrying

Running 115 worker on winVM, with --db-max_connections 50 (mysql on winVM, changed max connections of the db to 5000).
I guess that --db-max_connections will not help with 115 workers running and this is to be expected?

**Comment by majuss** [comment] 2016-08-16 18:17
Getting these deadlocks too, debian stable and mariaDB.

**Comment by FlarumHostingCo** [comment] 2016-08-16 18:24
I switched from InnoDB to MyISAM and no longer have the lock issue.

**Comment by rrbailey89** [comment] 2016-08-16 19:06
@FlarumHostingCo can you provide a guide for switching.  I'm using MariaDB.

**Comment by majuss** [comment] 2016-08-16 19:09
@FlarumHostingCo  I would also like a very quick guide.

**Comment by FlarumHostingCo** [comment] 2016-08-16 19:17
in my.cnf

under the section
[mysqld]

add or change default-storage-engine to:

default-storage-engine=MyISAM


Restart the SQL server and it should convert it.  If not, you'll need to drop and re-create your database.

**Comment by majuss** [comment] 2016-08-16 20:10
Didn't worked for me... "SET default_storage_engine=MyISAM;" dropped the db, restartet mysql. Still getting deadlocks :(

**Comment by Dagothur** [comment] 2016-08-17 07:04
Deadlocks are rampant if you have many processes: http://pastebin.com/adrFACgs

If a process gets stuck too long I have a script that kills it and restarts it which clears the log file... you can consider the timestamps for each dead lock line to get an idea of how frequently the issue is occurring.

**Comment by majuss** [comment] 2016-08-17 08:59
I also have multiple runserver with different locations... An option in the main runserver for different locations would solve the problem.

**Comment by Dagothur** [comment] 2016-08-17 09:00
Only for single server implementations

**Comment by totoberg123** [comment] 2016-10-02 17:02
Same problem since today

**Comment by sebastienvercammen** [comment] 2017-01-26 16:17
Issue is no longer related to the current codebase, so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.

**Closed by sebastienvercammen** 2017-01-26 16:17 UTC
Labels: backend, bug
