### ISSUE TITLE
Lured pokemons are shown as undefined

### ISSUE THREAD

**Issue by Shentang** [RocketMap/RocketMap#1027] opened 2016-08-27 13:17 UTC
## Expected Behavior

Pokemons should show up when clicking on Lured Pokestop
## Current Behavior

Undefined is being shown
![chrome_2016-08-27_14-53-58](https://cloud.githubusercontent.com/assets/17368229/18027639/6816b2e8-6c69-11e6-9402-e8afafb1587e.png)
## Possible Solution

No idea :<
## Steps to Reproduce (for bugs)
1. Find a lured pokestop
2. Click on it
## Context

Unable to check lured pokestops
## Your Environment

Python 2.7
Debian

**Comment by manzarek123** [comment] 2016-08-30 17:42
Lured pokemon are not shown.
Lot of other scanners have it I don't know why one of the biggest map project don't have it yet.
It has been weeks now....

**Comment by sebastienvercammen** [comment] 2017-02-23 13:12
Closing because the issue is much older than the current codebase. If your issue still persists, please make a new issue and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:12 UTC
