### ISSUE TITLE
Login for level 30 accounts is not retried when failing to login

### ISSUE THREAD

**Issue by z0n** [RocketMap/RocketMap#2006] opened 2017-05-01 15:00 UTC
## Expected Behavior
When the login of a level 30 account fails, the login should be retried after 6 seconds (as the log output states).

## Current Behavior
This doesn't happen and the account is put on hold.

## Steps to Reproduce (for bugs)

1. Use RocketMap with level 30 accounts and enable encounters
2. Have the login process of a level 30 account fail
3. ???
4. Profit

## Your Environment

* Version used: Latest develop build
* Environment name and version (e.g. Python 2.7): Pyton 2.7.13
* Operating System and version (desktop or mobile): Arch Linux
* Beehive with -st 14 and SpeedScan
* 25 workers per hive
* 1 L30 account per hive

Here's some log output (using -v):
```
2017-05-01 15:56:47,075 [  search-worker-22][      auth_ptc][    INFO] PTC User Login for: Level30Account1
2017-05-01 15:56:47,355 [   search-worker-0][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:47,358 [   search-worker-0][    schedulers][    INFO] Enumerating queue found no best location, with 27 claimed, 18 parked, 0 missed, 0 fresh band skips, 246 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:47,358 [   search-worker-0][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:47,657 [  search-worker-22][       account][   ERROR] Failed to login to Pokemon Go with account Level30Account1. Trying again in 6 seconds.
2017-05-01 15:56:47,891 [  search-worker-19][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:47,893 [  search-worker-19][    schedulers][    INFO] Enumerating queue found no best location, with 27 claimed, 18 parked, 0 missed, 0 fresh band skips, 246 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:47,893 [  search-worker-19][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:48,281 [  search-worker-24][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:48,283 [  search-worker-24][    schedulers][    INFO] Enumerating queue found no best location, with 27 claimed, 18 parked, 0 missed, 0 fresh band skips, 246 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:48,284 [  search-worker-24][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:48,738 [   search-worker-6][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:48,740 [   search-worker-6][    schedulers][    INFO] Enumerating queue found no best location, with 27 claimed, 18 parked, 0 missed, 0 fresh band skips, 246 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:48,741 [   search-worker-6][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:48,744 [  search-worker-13][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:48,746 [  search-worker-13][    schedulers][    INFO] Enumerating queue found no best location, with 27 claimed, 18 parked, 0 missed, 0 fresh band skips, 246 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:48,746 [  search-worker-13][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:48,952 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 1.
2017-05-01 15:56:49,007 [   search-worker-7][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:49,009 [   search-worker-7][    schedulers][   DEBUG] Enumerating queue found best location: {'loc': (50.7831886188118, 6.138303968171561, 187.183576076633), 'kind': 'spawn', 'secs_to_arrival': 0, 'end': 5187, 'i': 29, '
2017-05-01 15:56:49,009 [   search-worker-7][    schedulers][   DEBUG] step 345 start 3397 end 5187 secs to arrival 0
2017-05-01 15:56:49,009 [   search-worker-7][        search][   DEBUG] Scanning step 345 for a spawn.
2017-05-01 15:56:49,009 [   search-worker-7][        search][   DEBUG] Using key XXXXXXXXXXXXXXXXXXXXXXX for this scan.
2017-05-01 15:56:49,009 [   search-worker-7][       account][   DEBUG] Credentials remain valid for another 496.990653 seconds.
2017-05-01 15:56:49,009 [   search-worker-7][        search][    INFO] Scanning step 345 for a spawn.
2017-05-01 15:56:49,009 [   search-worker-7][        search][   DEBUG] Jittered to: 50.783212/6.138385/187.183576
2017-05-01 15:56:49,014 [   search-worker-7][          auth][   DEBUG] Session Ticket still valid for further 00:08:17 hours (1493647009014 < 1493647506744)
2017-05-01 15:56:49,058 [      db-updater-0][        models][   DEBUG] Upserted to MainWorker, 1 records (upsert queue remaining: 1) in 2.88 seconds.
2017-05-01 15:56:49,058 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 25.
2017-05-01 15:56:49,162 [      db-updater-0][        models][   DEBUG] Upserted to WorkerStatus, 25 records (upsert queue remaining: 0) in 0.10 seconds.
2017-05-01 15:56:49,268 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 1.
2017-05-01 15:56:49,360 [   search-worker-0][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:49,362 [   search-worker-0][    schedulers][    INFO] Enumerating queue found no best location, with 28 claimed, 17 parked, 0 missed, 0 fresh band skips, 246 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:49,362 [   search-worker-0][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:49,368 [      db-updater-0][        models][   DEBUG] Upserted to WorkerStatus, 1 records (upsert queue remaining: 0) in 0.21 seconds.
2017-05-01 15:56:49,433 [      wh-updater-1][       webhook][   DEBUG] Sending pokemon to webhook: MTUwODA0NzE0NDY1ODQ1NDg5ODA=.
2017-05-01 15:56:49,491 [   search-worker-7][        models][    INFO] Parsing found Pokemon: 1, nearby: 31, pokestops: 17, gyms: 1.
2017-05-01 15:56:49,491 [   search-worker-7][        models][   DEBUG] Skipped Pokemon: 0, pokestops: 17.
2017-05-01 15:56:49,541 [   search-worker-7][        search][   DEBUG] Search at 50.783189,6.138304 completed with 19 finds.
2017-05-01 15:56:49,541 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 1.
2017-05-01 15:56:49,593 [   search-worker-7][        search][   DEBUG] Skipping update of gym @ 50.784867/6.141709, up to date.
2017-05-01 15:56:49,593 [   search-worker-7][        search][    INFO] Search at 50.783189,6.138304 completed with 19 finds. Sleeping 9.673956s until 15:56:59.
2017-05-01 15:56:49,636 [      db-updater-0][        models][   DEBUG] Upserted to ScannedLocation, 1 records (upsert queue remaining: 4) in 0.27 seconds.
2017-05-01 15:56:49,636 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 1.
2017-05-01 15:56:49,732 [      db-updater-0][        models][   DEBUG] Upserted to Pokemon, 1 records (upsert queue remaining: 3) in 0.10 seconds.
2017-05-01 15:56:49,732 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 1.
2017-05-01 15:56:49,823 [      db-updater-0][        models][   DEBUG] Upserted to Gym, 1 records (upsert queue remaining: 2) in 0.09 seconds.
2017-05-01 15:56:49,823 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 1.
2017-05-01 15:56:49,895 [  search-worker-19][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:49,897 [  search-worker-19][    schedulers][    INFO] Enumerating queue found no best location, with 28 claimed, 17 parked, 0 missed, 0 fresh band skips, 246 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:49,897 [  search-worker-19][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:49,920 [      db-updater-0][        models][   DEBUG] Upserted to SpawnPoint, 1 records (upsert queue remaining: 1) in 0.10 seconds.
2017-05-01 15:56:49,920 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 1.
2017-05-01 15:56:49,974 [   search-worker-3][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:49,976 [   search-worker-3][    schedulers][   DEBUG] Enumerating queue found best location: {'loc': (50.79168387307228, 6.128847719448924, 156.25170617162698), 'kind': 'spawn', 'secs_to_arrival': 83.86238001011631, 'end
2017-05-01 15:56:49,976 [   search-worker-3][    schedulers][   DEBUG] step 47 start 3470 end 5260 secs to arrival 83.8623800101
2017-05-01 15:56:50,016 [      db-updater-0][        models][   DEBUG] Upserted to ScanSpawnPoint, 1 records (upsert queue remaining: 0) in 0.10 seconds.
2017-05-01 15:56:50,286 [  search-worker-24][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:50,288 [  search-worker-24][    schedulers][    INFO] Enumerating queue found no best location, with 28 claimed, 18 parked, 0 missed, 0 fresh band skips, 245 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:50,288 [  search-worker-24][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:50,743 [   search-worker-6][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:50,745 [   search-worker-6][    schedulers][    INFO] Enumerating queue found no best location, with 28 claimed, 18 parked, 0 missed, 0 fresh band skips, 245 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:50,745 [   search-worker-6][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:50,749 [  search-worker-13][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:50,750 [  search-worker-13][    schedulers][    INFO] Enumerating queue found no best location, with 28 claimed, 18 parked, 0 missed, 0 fresh band skips, 245 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:50,751 [  search-worker-13][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:51,368 [   search-worker-0][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:51,369 [   search-worker-0][    schedulers][    INFO] Enumerating queue found no best location, with 28 claimed, 18 parked, 0 missed, 0 fresh band skips, 245 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:56:51,369 [   search-worker-0][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:56:51,898 [  search-worker-19][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:56:51,900 [  search-worker-19][    schedulers][    INFO] Enumerating queue found no best location, with 28 claimed, 18 parked, 0 missed, 0 fresh band skips, 245 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:57:14,788 [   search-worker-6][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:57:14,791 [   search-worker-6][    schedulers][    INFO] Enumerating queue found no best location, with 30 claimed, 18 parked, 0 missed, 0 fresh band skips, 243 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:57:14,791 [   search-worker-6][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:57:14,792 [  search-worker-13][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:57:14,794 [  search-worker-13][    schedulers][    INFO] Enumerating queue found no best location, with 30 claimed, 18 parked, 0 missed, 0 fresh band skips, 243 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:57:14,794 [  search-worker-13][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:57:14,888 [  search-worker-20][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:57:14,890 [  search-worker-20][    schedulers][   DEBUG] Enumerating queue found best location: {'loc': (50.789795122461896, 6.146043177632809, 172.23972018623), 'kind': 'spawn', 'secs_to_arrival': 0, 'end': 5190, 'i': 30,
2017-05-01 15:57:14,890 [  search-worker-20][    schedulers][   DEBUG] step 221 start 3400 end 5190 secs to arrival 0
2017-05-01 15:57:14,890 [  search-worker-20][        search][   DEBUG] Scanning step 221 for a spawn.
2017-05-01 15:57:14,890 [  search-worker-20][        search][   DEBUG] Using key XXXXXXXXXXXXXXXXXXXXXXX for this scan.
2017-05-01 15:57:14,891 [  search-worker-20][       account][   DEBUG] Credentials remain valid for another 477.108956 seconds.
2017-05-01 15:57:14,891 [  search-worker-20][        search][    INFO] Scanning step 221 for a spawn.
2017-05-01 15:57:14,891 [  search-worker-20][        search][   DEBUG] Jittered to: 50.789872/6.146001/172.239720
2017-05-01 15:57:14,905 [  search-worker-20][          auth][   DEBUG] Session Ticket still valid for further 00:07:57 hours (1493647034905 < 1493647512516)
2017-05-01 15:57:15,248 [      db-updater-0][        models][   DEBUG] Inserting items 0 to 1.
2017-05-01 15:57:15,354 [      db-updater-0][        models][   DEBUG] Upserted to WorkerStatus, 1 records (upsert queue remaining: 0) in 0.87 seconds.
2017-05-01 15:57:15,411 [   search-worker-0][    schedulers][    INFO] Enumerating 291 scan locations in queue.
2017-05-01 15:57:15,413 [   search-worker-0][    schedulers][    INFO] Enumerating queue found no best location, with 31 claimed, 17 parked, 0 missed, 0 fresh band skips, 243 missed because we're early, 0 because we're too late. Minimum
2017-05-01 15:57:15,413 [   search-worker-0][    schedulers][   DEBUG] step 0 start 0 end 0 secs to arrival 0
2017-05-01 15:57:15,420 [      wh-updater-2][       webhook][   DEBUG] Sending pokemon to webhook: MjEzNTk3NzA4MTE2MTc3MDU1Ng==.
```
At 15:56:47, the login for the L30 account failed but there no retry following after 6 seconds.
At 15:59:18, the encounter is skipped and transmitted to the webhook without IV/CP:
```
2017-05-01 15:59:18,803 [   search-worker-6][        models][   ERROR] No L30 accounts are available, please consider adding more. Skipping encounter.
2017-05-01 15:59:18,804 [      wh-updater-2][       webhook][   DEBUG] Sending pokemon to webhook: MTk4NzIwNTkwODk2MjI4ODc0NQ==.
```
I suspect that this is still the Pokémon which should have been encountered at 15:56:47 because it was reported to the webhook with a remaining time of 26m 46s.

Seems like something is wrong with the retry behavior of L30 accounts, feel free to ask for more information if you need it.

**Comment by Obihoernchen** [comment] 2017-05-01 15:21
Try https://github.com/RocketMap/RocketMap/pull/2004

**Comment by z0n** [comment] 2017-05-01 15:27
I'm already running #2004 as this was merged. :/

**Comment by sebastienvercammen** [comment] 2017-05-03 16:31
@z0n Are you 100% sure the missing part of the log does not contain the following message?

> Failed to login to Pokemon Go with account %s in %d tries. Giving up.

The timing can be off, it's not necessarily 6 seconds due to how threading works, it's *at least 6 seconds*.

I checked the procedure responsible for logging in an account, and that single procedure handles the login, login exceptions, login retries, **and** the error messages mentioned in this thread, so all accounts (regular and L30) are handled in 100% the exact same way, with the exact same procedure.

**Comment by z0n** [comment] 2017-05-03 20:37
@sebastienvercammen 
I don't have the logs for this incident anymore unfortunately. Something seems to be off about the logging itself though.
I see less log messages about encounters than I'm expecting.
For example, there was a successful encounter in one hive which looked like this:
```
$ journalctl --no-pager -b --unit pokemap@07 --since "2017-05-03 21:20" -o cat | grep -i encounter
2017-05-03 21:21:38,964 [        MainThread][     runserver][    INFO] Encountering pokemon enabled.
2017-05-03 21:33:32,402 [  search-worker-21][        models][   DEBUG] Encountering Pokémon ID 147 with account LVL30Acc1 at 50.8107761994, 6.11370664843.
2017-05-03 21:33:32,403 [  search-worker-21][        models][   DEBUG] Using hashing key XXXXXXXXXXXXXXXXXX for this encounter.
```
This encounter was successful (= IV/CP sent to the webhook and written to the database), the `Encounter for Pokémon ID %s at %s, %s successful: %s/%s/%s, %s CP.` log entry is missing though.
A few seconds after this event, another Pokémon which should have been encountered spawned but it was simply sent to the webhook without IV/CP. It couldn't be encountered because the only L30 account in this hive was in cooldown (at least I think it works this way?). The logs don't even show any attempt to encounter this Pokémon though.

So maybe there was the event you described (`Failed to login to Pokemon Go with account %s in %d tries. Giving up.`) but it wasn't written to the logs.

**Comment by dsorc** [comment] 2017-05-14 11:43
I have the same problem

The level 30 account pool is gradually getting smaller if the scan is not restarted regularly. (a few lost per day)
Restarting the scan shows no captchas and all accounts are OK again.

Error in log:
No L30 accounts are available, please consider adding more. Skipping encounter.

Settings:
30 L30 accounts
hlvl-kph: 750 (very fast)
ST 67
Encounters per minute 10-20 (pretty high)

Last login:
2017-05-13 21:31:54,759 [search-worker-174][        models][   DEBUG] Encountering Pokémon ID 133 with account NAME
2017-05-13 21:31:54,759 [search-worker-174][       account][   DEBUG] Credentials remain valid for another 1462.240000 seconds.
2017-05-13 21:31:54,760 [search-worker-174][          auth][   DEBUG] Session Ticket still valid for further 00:24:22 hours (1494700314761 < 1494701777471)

The log goes on for another 300MB, no mention of that account is made again.

I still have the log is there is something I should search for.

**Comment by h0us3cat** [comment] 2017-05-16 22:32
I can confirm the above, accounts didnt login because ptc was down.
Normal workers did login after ptc server came back.

**Comment by evilmoses** [comment] 2017-05-18 08:35
Yup, exactly the same issue I have. After about 8 hours there are no lvl 30 accounts available in the pool. A restart gets them all back into the pool. I have turned logging on for a small scans and will post results here.

**Comment by jorgitoh** [comment] 2017-05-25 06:26
@dsorc are u using kph 750 with lvl 30 acc? Any risk?

**Comment by dsorc** [comment] 2017-05-25 07:32
@jorgitoh Yes, out of my 30 level 30 accounts the topmost 15 have been shadow banned.
I was doing about 40 encounters per minute, and the topmost accounts in the list kept being used again and again.
Now I use the normal speed (35 kpm I think) and only scan a few super rares per hour (RIP IVs) so I don't get my remaining accounts flagged.

**Comment by sebastienvercammen** [comment] 2017-07-29 12:39
Accounts aren't instantly retried, but they also aren't put on indefinite lockdown since #2139. Closing issue, but feel free to comment if it persists.

**Closed by sebastienvercammen** 2017-07-29 12:39 UTC
