### ISSUE TITLE
[Bug] Lured Pokemon not showing type

### ISSUE THREAD

**Issue by johnkernke** [RocketMap/RocketMap#274] opened 2016-08-09 09:47 UTC
In the info box for a lured Pokemon it does not show its type, eg. water, ground, fire, etc. It is fine for regularly spawned Pokemon.
## Expected Behavior

Info box should have Pokemon types
## Current Behavior

as above.
## Possible Solution

Some function probably isn't getting called for lured Pokemon
## Steps to Reproduce (for bugs)
1. Use latest map version
2. Open map
3. See lured Pokestop
4. Hover over Pokemon spawned by pokestop
## Your Environment
- Version used: c14d53b (latest as of posting)
- Environment name and version (e.g. Python 2.7): Python2.7
- Operating System and version (desktop or mobile): Debian 8 (Server), Chrome v52

**Comment by sebastienvercammen** [comment] 2017-02-23 13:04
Closing because the issue is much older than the current codebase.

**Closed by sebastienvercammen** 2017-02-23 13:04 UTC
Labels: bug, frontend, minor
