### ISSUE TITLE
Incorrect Lure Expiration Time Display for Lured Pokestop

### ISSUE THREAD

**Issue by clifford2006** [RocketMap/RocketMap#689] opened 2016-08-15 03:15 UTC
## Expected Behavior

The lured pokestop should display the correct expiration timer.

## Current Behavior

Everytime when you refresh the browser, the expiration time seems to be increased until the real expiration ends.

## Possible Solution

Found the problem in map.js
Line 1071: var timeUntilExpire = currentDate.getTime() - lastModifiedDate.getTime();
This causes the time until expire to increase until 30minutes where the pokestop expires.
It should be var timeUntilExpire = currentDate.getTime() - lure_expiration;
Not lastmodifieddate

Pull Request #555 can also be a solution to this as well.

## Steps to Reproduce (for bugs)

1. Run Pokemon Live on browser (Google Chrome for me)
2. Check one of the lured pokestop expiration timer
3. Refresh browser and check again.
4. Repeat Step 3 and you will notice the expiration kept on increasing until it really expires.
## Context

You doesn't really know when does the pokestop expires, although you still can know that the pokestop is still lured or not.
(Update) The pokestop still expires at the lure_expiration as indicated in database, the only thing that is messed up is the display on browser.

## Your Environment

- Version used: Latest stable release: https://github.com/PokemonGoMap/PokemonGo-Map/releases/tag/v3.1.0
- Environment name and version: 2.7.12
- Operating System and version: Desktop (Window 10, Google Chrome)

**Comment by Shobba** [comment] 2016-08-15 20:15
Jap, Pull Request #555 should fix this at least temporarily. But there's also a discussion in that PR about what changed about (lured) pokestops and why it's difficult to display lure data correctly. Nevertheless the fix in my PR definitely is better than what is currently there.

**Comment by Darkknightz** [comment] 2016-10-13 11:56
#555 merged and this should be closed :)

**Comment by sebastienvercammen** [comment] 2017-02-23 13:06
Closing because the issue is much older than the current codebase and it's reported as solved. If your issue still persists, please make a new issue and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:06 UTC
