### ISSUE TITLE
Problem when turning on notifications on Android Chrome

### ISSUE THREAD

**Issue by Okumba** [RocketMap/RocketMap#418] opened 2016-08-10 13:23 UTC
When I turn on notifications (either for a pokemon or rarity) and a pokemon is shown on the map that would trigger the notification the whole process stops there. No notification is shown, no other pokemons will be loaded on the map (but the ones that were loaded before the pokemon that raised the notification). It is like the site crashes or something. Removing the notification pokemon from the the notification list and reloading the site helps.

Using: Android Chrome Version 52.0.2743.98 on Android 5.1.1

On Desktop Chrome (Win) it is working

**Comment by Wesleyl89** [comment] 2016-08-10 13:38
Yes same here

Using: Android Chrome Version 52.0.2743.98 on Android 6.0.1

**Comment by tkSimon** [comment] 2016-08-10 17:54
same here, Android 6.0.1

**Comment by DiscoTim** [comment] 2016-08-10 18:47
the way it works now crashes the script. audio.play() won't work without user interaction and "new notification" is not supported, it requires register service worker instead.

i ended up using https://github.com/CreateJS/SoundJS and https://github.com/Nickersoft/push.js to get these working properly cross platform.

**Comment by Studio-XP** [comment] 2016-08-10 21:52
It's due to `new Notification` not being supported in Chrome for Android, thus causing JS to crash.  Unfortunately I'm inexperienced with GitHub, but I've provided my changes to make it not only not crash the page, but also give mobile users their own notification (vibrate). static/map.js

```
function sendNotification (title, text, icon, lat, lng) {
  if (!('Notification' in window)) {
    return false // Notifications are not present in browser
  }

  if (Notification.permission !== 'granted') {
    Notification.requestPermission()
  } else {
    var notification = new Notification(title, {
      icon: icon,
      body: text,
      sound: 'sounds/ding.mp3'
    })

    notification.onclick = function () {
      window.focus()
      notification.close()

      centerMap(lat, lng, 20)
    }
  }
}
```
to
```
function sendNotification (title, text, icon, lat, lng) {
  if (!('Notification' in window)) {
    return false // Notifications are not present in browser
  }

  if (Notification.permission !== 'granted') {
    Notification.requestPermission()
  } else {
	try {
		var notification = new Notification(title, {
		  icon: icon,
		  body: text,
		  sound: 'sounds/ding.mp3'
		})

		notification.onclick = function () {
		  window.focus()
		  notification.close()

		  centerMap(lat, lng, 20)
		}
	} catch (e) {
		if (e.name === 'TypeError') {
            navigator.vibrate(1000)
        }
    }
  }
}
```

**Comment by eeg710** [comment] 2016-08-10 22:42
Why does it need to be under ssl?

**Comment by DiscoTim** [comment] 2016-08-10 22:48
its a requirement in android chrome, geolocation requires it as well. it will work on local host without ssl.

**Comment by UwV2000** [comment] 2016-08-11 20:43
notifications works ok in firefox.

**Comment by Studio-XP** [comment] 2016-08-11 20:50
Are you referencing Firefox for Android or desktop?

**Comment by Zentriert** [comment] 2016-08-11 20:58
I just tested it in Firefox for Android and it worked fine. Notified me of a Weedle spawn.

I didn't test for notification sound because I had mine silenced.

**Comment by Studio-XP** [comment] 2016-08-11 21:06
Ok, just installed Firefox and both the current sound and push notifications are working. I guess Chrome is more restrictive.

With @DiscoTim's help, I was able to get the audio notification working on Chrome for Android. Now on to the push.js

**Comment by UwV2000** [comment] 2016-08-11 21:15
srry yes firefox for android

**Comment by sebastienvercammen** [comment] 2017-02-23 13:05
Closing because the issue is much older than the current codebase. If your issue still persists, please make a new issue and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:05 UTC
Labels: bug, frontend, has pr
