### ISSUE TITLE
Improvements to front end interface - what is feasable, what should we be working on?

### ISSUE THREAD

**Issue by khag7** [RocketMap/RocketMap#1278] opened 2016-09-12 13:36 UTC
I have an interest in improving the front end. I have more interest than I have time, but I'll do what I can. 

Anyone else with time on their hands, this is some stuff I think could be knocked out and I can help you along the way! Please join in and claim a task and lets get some PR's going for this stuff!

Anyone with criticisms please share!
## New optional config file called web_interface.json:
- ability to diasable any individual options from the front end
- ability to set up login credentials (basic http auth, nothing fancy)
- ability to define a timeout value which will pause scanning if reached
- ability to set default options for the front end
- move ssl config.ini options to here
- move gmaps key to here - actually probably not since its required in core for searching
- move status page password to here
- move host and port here
- move locale to here
- define additional named locations ( like Home: Lat, Lng and Work: Lat, Lng ) so we can move searches
- define additional named spawnpoint files here ( like City1: c1.json and City2: c2.json ) to switch files from web
- probably some other things would make sense to move to here
## Web server updates:
- basic http auth (credentials defined in json file mentioned above)
- provide default options from json defined above
- handle blocking/removing options based on json above
## Arguments parser updates:
- Update arguments parser to parse from json
- Update arguments parser to accept accounts in json format as well as CSV
- Update arguments parser to accept config as json as well as ini
## Search code updates:
- Ability to pause/unpuase scanning
- Track how much time has passed since last http request
- Pause scanning if http request timeout is reached
- Unpause/reset timer when a new request is made
- Ability to do a single on-demand scan (i.e. pause after the hex sprial is finished)
  - this only applies to spiral scanning, spawnpoint is continuous so there is no "end"
- Ability to change options while paused/stopped
  - i.e. stop scanning, change scan method to hex scan, restart scanning
  - probably would be useful for scan method, step size, scan delay, gyms on/off, pokestops on/off, etc.
  - eventually this could lead us towards developing an interface for all config settings instead of using notepad for config.ini, we can store all settings as json and allow them to be updated in browser. some would require scan to stop, setting change, then scan start. others would change the json but require a restart of the process (manually)
## Update the "Location & Search Settings" menu:

![image](https://cloud.githubusercontent.com/assets/1531746/18438099/f1c38c4e-78cd-11e6-89bd-b906fc7ddcf3.png)

| Option | Values | Explanation |
| --- | --- | --- |
| **Scan Method** | dropdown opts: |  |
|  | Spiral (Default) | The normal hex scan (this will enable the On Demand option in Repition settings) |
|  | Spiral (Skip Empty) | Hex but skip locations with no predicted active spawnpoints (-ss) |
|  | DB Spawnpoints | Use spawnpoints from DB |
|  | Spawnpoints file 1 | Use custom named spawnpoints from spawnpoints file if provided (otherwise this option won't show) |
|  | Spawnpoints file 2 | Use custom named spawnpoints from another spawnpoints file if provided (otherwise this option won't show) |
| **Scan Repetition** | dropdown menu opts: |  |
|  | Continuous | Current functionality (but will be overridden with the search toggle in the nav bar) |
|  | Timeout | This is effectively "continuous" but with a timeout - this option won't show if timeout isn't defined in config.ini |
|  | On Demand | This is effectively "disabled" but a button will be in nav bar to do a single one time scan (will only show if method is "spiral" since there is no end to spawnpoint scanning) |
| **Scan Location** | dropdown menu opts: |  |
|  | Locked (Default) | Uses the location from location in config.ini, don't allow marker to be moved |
|  | My Location | Updates location every time My Location changes |
|  | Location1 | Sets location to a custom named location defined in config.ini |
|  | Location2 | Sets location to a custom named location defined in config. |
|  | Custom | Shows the search text box for user to search for a location |
| **My Location** | dropdown menu opts: |  |
|  | Update Automatically | Move my location automatically (this won't move search location, that's a different option) |
|  | Update Manually | Only move my location when the button is clicked in the bottom right corner of map |
| **Center Map** | dropdown menu opts: |  |
|  | Manually (defualt) | Don't recenter the map |
|  | Scan Location | When scan location moves, center the map |
|  | My Location | When my location moves, center the map |
| **3 New Nav Bar Items** | (only one at a time will be shown) |  |
| button | "Scan Now" | If scanning repetition is "On Demand" this button will start a single scan (note: On Demand is not available if method doesn't support it (i.e. spawnpoint scanning) ) |
| button | "Stop Scanning" | If scanning repetition is "On Demand" this button will stop the scan |
| toggle | "Scanning" | If scanning repetition is continuous or timeout, this toggle will start/stop scanning |

![image](https://cloud.githubusercontent.com/assets/1531746/18438374/12ea358e-78cf-11e6-8065-7f30363164d0.png)

![image](https://cloud.githubusercontent.com/assets/1531746/18438242/7b6de778-78ce-11e6-89ce-bd59f7d6248a.png)

![image](https://cloud.githubusercontent.com/assets/1531746/18438343/ef58f0c4-78ce-11e6-8d8b-7054b0d74140.png)

**Comment by nhumber** [comment] 2016-09-12 16:00
any chance you can fix/work around/change mouse over trainer names on mobile devices?

**Comment by Xcelled** [comment] 2016-09-12 18:17
Related: #1141

**Comment by khag7** [comment] 2016-09-12 21:02
@Xcelled that's VERY related, I'm sorry I didn't see that, I might have just posted some of this there instead. Didn't intend to hijack you! Either way, I'm glad to see some other folks with similar thoughts.

If we can get pause/unpause set up and working in the search code, all the other features we want to implement will be feasible without editing much python. Its mostly js and html at that point. Which means a lot more people can participate here to improve the web side (since I keep hearing people, including myself, say they don't develop much here because its out of their realm of experience)

**Comment by Xcelled** [comment] 2016-09-12 21:06
@khag7 your writeup is much more detailed than mine :p I like your ideas, and I agree - if the project is restructured a little, I think it's for the best.

**Comment by DiscoTim** [comment] 2016-09-12 21:45
This is all pretty good, just a couple comments.

I'd like to see the admin type options, the options that effect all users, separated from the user type options, the options that only effect the individual user, perhaps on an /admin endpoint. Many people share their their maps with family and friends and not all options apply to everyone and is just clutter and confusing. 

The options layed out for My Location are just manual/automatic, so a toggle, i like that the center-map is moved to a separate option. In manual mode, i think it should also remain dragable, like it is now.

i've also seen the default zoom come up a couple of times, which is set at 20, and some feel that is too close.

notifications arn't mentioned here, and it's a HUGE gap in this project, maybe its out of scope of this rfc. I think a lot of people just assume to just use pokealarm. pokealarm is only useful when the map has a single user, or an absolute set of users, but i don't think that is typical use. its not useful when the map is shared with family and friends and other semi-random people. i am not referring to public use, which i know is not supported, i think that is typical use.

**Comment by jorgebsa** [comment] 2016-09-12 22:05
> notifications arn't mentioned here, and it's a HUGE gap in this project, maybe its out of scope of this rfc. I think a lot of people just assume to just use pokealarm. pokealarm is only useful when the map has a single user, or an absolute set of users, but i don't think that is typical use. its not useful when the map is shared with family and friends and other semi-random people. i am not referring to public use, which i know is not supported, i think that is typical use.

@DiscoTim  I tend to disagree. An example from my usage: i've created a few telegram groups, one for each neighborhood i'm usually going to scan (i'm not a 24/7 scanner), invited a couple of friends to those groups and shared my telegram bot api key and chat ids with both of them. Whenever one of us is scanning one of those neighborhoods, we all get notified, and we also know that we can focus on scanning another one since that one is taken care of already (we don't share DBs)

But yea, everyone has their/different needs

**Comment by DiscoTim** [comment] 2016-09-12 22:28
@jorgebsa i agree that everyone has different use cases. i am referring to what i think is probably the most common use case. in your case you are all running scanners, and sharing api keys? it seems all of this has to be pre-arranged and not just a simple, drop someone a url. what do you get notified for, and who determines that?

**Comment by jorgebsa** [comment] 2016-09-12 22:36
@DiscoTim we don't share maps, each one of us runs their own web server, database and webhooks however they see fit. However, our webhooks (pokealarm) are configured using same bot api key and a chat id for each area of interest, so that everyone gets notified even if they are not scanning such areas. Probably not the most common use case, but who knows which case is truly the most common haha

**Comment by khag7** [comment] 2016-09-13 11:42
@jorgebsa I like that group notification idea. It makes sense to share notifications but still keep your own maps. 

@DiscoTim As with many things in this repo, there was a good fix for notifications a few weeks ago which never got merged. Check out #623 and #866

**Comment by Xcelled** [comment] 2016-09-13 17:44
@khag7 That's my major barrier to contributing - pull requests are left to stagnate (97, really?) instead of being closed/commented/merged. Tends to give the impression that help won't be appreciated...

**Comment by DiscoTim** [comment] 2016-09-13 20:08
@khag7 thanks, i am aware :) i helped with #623 and I have #933 myself which is fully functional, and quite a few people are using. Point is, there STILL isn't official working notifications on android, and is exactly what @Xcelled is touching on.

that aside,
I've been looking at a few of these type of libs https://github.com/joshfire/jsonform , which might be helpful for front end json work.

there is currently a pr for the pause/unpause type scanning you're mentioning, and i think localization should receive some attention as well.

**Comment by khag7** [comment] 2016-09-13 21:46
I am finishing up a PR for a totally unrelated feature but this is my next priority. I will use the PR already out there for pause/unpause and base my changes off that, re-doing the settings as I mocked up in the screenshots above.

My plan then is to look into moving config files from ini to json and once thats done we can look at how to use something like jsonform to edit the config files from the web. I guess somewhere in between those steps we also need to determine which settings are "user" settings and which are "admin". Ugh.. that brings up another point I meant to mention in the original post... if we have user based settings, we might want to look into storing those for users. Right now everything is in browser storage so if I set up an ignore list on my desktop browser and then open my mobile, the list isn't the same. Storing a users settings as json in our db (do we need a users table now? or a settings table? ... shit if we do a settings table maybe we don't even store settings in json at all anymore. fuck this is turning into a whole thing)

**Comment by Xcelled** [comment] 2016-09-14 03:04
@khag7 you almost need the ability to do accounts/authentication. Could have a 'guest' account that stores nothing and basically behaves as it is now. I wonder if flask provides auth stuff like Django does...

**Comment by khag7** [comment] 2016-09-14 09:32
@xcelled if we wanted to half-ass it we could use basic http auth. no registration page or anything, the admin could list usernames & passwords as plaintext in a json file or csv or whatever. shit, even a textarea input in the "admin area" page. whatever. they get saved in a server settings json or in our server settings db table and when the server starts (and maybe once every 60 seconds?) the http auth function we'll put in runserver.py will pull the list of usernames & passwords to check against. 

but yeah, much better to use real auth if its available easily

**Comment by DiscoTim** [comment] 2016-09-14 11:25
There's been previous pr's for auth and they've been shutdown re. 'beyond the scope of this project'.

I think these are the main usage scenarios of this project, there are others, but i think these are the majority:

1. single user, single admin. visualizing, data analysis, the project itself. catching pokemon..
2. multi user, single admin. Sharing map with friends/family/co-workers/town/dorm/etc.. and in many cases includes #1 as well... not public usage.. which is not supported.

The needs are different but largely the same, some overlap, and some are undesirable to the other.

A quick search brings up these, which all seem suitable for basic stuff, some more so than others:

https://pythonhosted.org/Flask-User/
https://github.com/maxcountryman/flask-login
https://pythonhosted.org/Flask-Security/

There is some real benefits to being able to store settings against a user. the most obvious is your settings follow you between devices, but also would facilitate things such as.. notifications.. where the user enters their info on the front end and the backend sends out the notifications through telegram or whatever.. which would overcome some of the current limitations of things like pokealarm being (basically) single user or ios not supporting web notifications.

**Comment by FrostTheFox** [comment] 2016-09-21 02:36
@Xcelled We're working our best to PRs. In case you haven't noticed, I've been the only person merging things recently. Lots of people have left the team so some of the PR crew has helped me with picking up the load. The "(97? Really?)" is not needed. We're well aware of the PR backlog, and are trying to work with PR creators in the discord to fix things and get their PRs merged whenever we can.

**Comment by sebastienvercammen** [comment] 2018-01-25 13:16
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.

**Closed by sebastienvercammen** 2018-01-25 13:16 UTC
Labels: front-end
