### ISSUE TITLE
Delete pokemon from notify/exclude list not working properly

### ISSUE THREAD

**Issue by aldarund** [RocketMap/RocketMap#835] opened 2016-08-19 09:55 UTC
when there a lot items ( more than a textrea so scrollbar appear) deleting become really hard, because clicking on x on delete dont delete but scroll to the bottom and open autocomplete list. It actually may work after 3-5 try. Quite annoying :)
Behave same on both phone and desktop.

**Comment by justsomedudeonthenet** [comment] 2016-08-19 12:20
In addition, at least on android, removing an item makes the on screen keyboard popup, which shifts the whole page and makes it very hard to delete a bunch at once.

**Comment by DiscoTim** [comment] 2016-08-24 22:07
In addition, just touching the box on android makes the on screen keyboard appear, covering the selections. touch box -> minimize keyboard -> select an item.. rinse.. repeat

**Comment by DiscoTim** [comment] 2016-08-25 02:24
Seems to be a long standing issue with select2, https://github.com/select2/select2/issues/1541

I hacked it with this, sooo much better, working so far on chrome android anyways.

```
  $('select').each(function () {
    $(this).on('select2:open', function(e) {
      $('.select2-search input').blur();
    }).on('select2:close', function(e) {
      $('.select2-search input').blur();
    })
 });
```

**Comment by sebastienvercammen** [comment] 2017-02-23 13:08
Closing because the issue is much older than the current codebase. If your issue still persists, please make a new issue and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:08 UTC
