### ISSUE TITLE
Gym filter persists to raid filter even when disabled

### ISSUE THREAD

**Issue by Ben-13** [RocketMap/RocketMap#2268] opened 2017-08-22 00:20 UTC
## Expected Behavior

Within webview if you set a gym filter , eg team specific, empty slot etc then disable gyms then enable raid filters you should see the raids that match your filter.

## Current Behavior
The gym filter persists even when disabled/unchecked and you only see the raids that ALSO match the gym filter.

## Steps to Reproduce (for bugs)
1. navigate to map, disable all options
2. enable gyms, set gym filter to only show mystic
3. disable gym filter
4. enable raid filter and note number/location of raids
5. disable raid filter
6 enable gym, set back to defaults (all teams, raids 1-5 and uncheck "empty slot")
7 disable gym
8 enable raids and compare number/locations to number from step 4

## Context
may not be obvious that you are not seeing all raids as they are still filtered

## Your Environment
windows, python 2.7

**Comment by tomballgithub** [comment] 2017-08-26 05:24
I agree with this issue.  It took someone else using my map to finally figure out what the root cause of this frustrating issue was.  It's not intuitive at all that the disabled gyms button could have anything to do with raids not showing up.  I came in here to write the issue up and found that you beat me to it.

**Comment by tomballgithub** [comment] 2017-08-26 05:25
If you have the settings for gyms very restrictive, it is very obvious that something is wrong because you might just have a few raids showing up.  If you have the settings slightly restrictive, it may not be obvious at all.  Really need this fixed.

**Comment by BrownSlaughter** [comment] 2017-08-27 21:07
I have sorted a quick fix for this issue that will reset the gym filters when you disable it, I will test it in the morning and then push a PR for testing.

**Closed** 2017-09-21 14:39 UTC
Labels: confirmed, has pr
