### ISSUE TITLE
Lured stops being overwritten

### ISSUE THREAD

**Issue by FroznArrow** [RocketMap/RocketMap#667] opened 2016-08-14 17:54 UTC
Currently, 
Lured stops show up, I can see what pokemon it lured, I can see the lured pokemon on the map... 
But once the scan circle passes the area and moves onto the next scan, the lured stop gets overwritten, and the stop doesn't show that it's still lured, although I can still see the lured pokemon on the map.

![ss 2016-08-14 at 10 39 29](https://cloud.githubusercontent.com/assets/20621826/17650841/b921bbd6-620c-11e6-811f-73f53ea70d0b.png)
![ss 2016-08-14 at 10 38 16](https://cloud.githubusercontent.com/assets/20621826/17650840/b91e0fd6-620c-11e6-902f-f855b1ee5566.png)
![ss 2016-08-14 at 10 38 27](https://cloud.githubusercontent.com/assets/20621826/17650839/b91d7f1c-620c-11e6-9ded-14726203ce8a.png)

**Comment by SkOODaT** [comment] 2016-08-14 19:31
its a known problem recently Niantic changed the api a tiny bit people have been working on it, some of the development builds have the lures working again but pokemon have been removed id love to get an update too on this as its a major needed feature so many lures and no way to see what pokes are at them lol
https://github.com/PokemonGoMap/PokemonGo-Map/issues/516

**Comment by FroznArrow** [comment] 2016-08-14 20:19
I fixed the lured pokemon issue recently based on a few PRs here, and they show up properly...
But I need to be able to see where the lures are still active.

Right now, I'm just guessing which lures are active based on the proximity of pokemons next to stops

**Comment by SkOODaT** [comment] 2016-08-14 20:23
any chance you be willing to share your fix ? if you look at the link i posted lured stops are passing some type of modifier back to IS them as lured should be easy enough for you to fix in your PR

**Comment by FroznArrow** [comment] 2016-08-14 21:21
I don't remember what I fixed, I'm also running on an old commit with some minor modifications.

**Comment by blastagator** [comment] 2016-08-15 02:35
Create a new commit and then push it to your tree on github.  Then you can look at the commit and easily see the changes that have been made :)

**Comment by sebastienvercammen** [comment] 2017-02-23 13:06
Closing because the issue is much older than the current codebase and it's reported as solved with #1303. If your issue still persists, please make a new issue and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:06 UTC
