### ISSUE TITLE
Captcha's are not always detected on login.

### ISSUE THREAD

**Issue by daangroot** [RocketMap/RocketMap#2365] opened 2017-11-01 16:52 UTC
Captcha's on accounts that have a captcha before RM has logged in to the account are sometimes not detected.

## Current Behavior

When RM logs in to an account that has a captcha, it sometimes doesn't detect the captcha and will just use it.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by pogo-excalibur** [comment] 2017-11-02 20:32
This looks like a duplicate of #2267.

**Closed** 2017-11-02 21:02 UTC
