### ISSUE TITLE
Restore Lured Pokemon & Continuous Miner Feature

### ISSUE THREAD

**Issue by Sammy-L** [RocketMap/RocketMap#516] opened 2016-08-11 19:29 UTC
## Current Behavior

According to #493 , it fixed the lure pokestops problem. However the information what pokemon lured is lost.
I'm now using an older map version. I found from MySQL DB result that active_pokemon_id is actually returned and logged. But it's soon (less than a second) turned back to NULL.
![screen shot 2016-08-12 at 3 13 12 am](https://cloud.githubusercontent.com/assets/20768040/17603253/d6d93cb0-6042-11e6-90f6-e7ebf67183be.png)

## Possible Solution

It seems that active_pokemon_id is returned when the scan area hits exactly the lured pokestops. That's why it's soon turn to NULL in the next query update by another worker thread. As #493 explains, only a active_fort_modifier is returned if the scan is too far from the lured pokestop. In any case, there is no encounter_id returned.
Possibly we would cache the active_pokemon_id when the scan returns a good value.

**Comment by invisiblek** [comment] 2016-08-12 03:36
I'm on board with fixing this properly, but my only current idea (dedicating searchers to sit at lured pokestops when you find them) is not something I'd be too fond of for a couple reasons. You'd have to pull out a searcher from your main searcher pool to sit at the pokestop (one for each lured pokestop) which is both complicated and detrimental to your all around scanning threads.

Totally open to ideas here...

**Comment by Sammy-L** [comment] 2016-08-12 10:58
I'm not familiar with python but here's my general thought about the fix. First, when one of the scans spot a valid active_pokemon_id and lure_expiration, write them to DB. Add a WHERE clause to upsert queries to check if lure_expiration > CURRENT_TIMESTAMP. Overwrite it with NULL or any new scan results if true; if not expired, don't do anything to the record.

**Comment by antiroot** [comment] 2016-08-12 14:22
I like the idea of two separate types of search workers, my only request is that the number of lure workers be configurable. Some towns/small maps may only need one, but cities/large maps may need several to be able to scan all the lures to detect the spawns before they expire

**Comment by sebastienvercammen** [comment] 2017-02-23 13:05
Closing because the issue is much older than the current codebase. If your issue still persists, please make a new issue and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:05 UTC
Labels: backend, bug
