### ISSUE TITLE
Exception leading to sleep

### ISSUE THREAD

**Issue by shivampaw** [RocketMap/RocketMap#1253] opened 2016-09-10 04:57 UTC
So basically my workers (I think I have around 71) will all go up to 71 successes and then all fail with one exception which I haven't seen yet and then they go into ages of sleeping and "Waiting for a new account from the queue".

This is probably a bug because if I restart or just wait for like 2 hours I think it is it works fine.

Using mysql

**Comment by justsomedudeonthenet** [comment] 2016-09-10 05:09
What is the exception error?

If you run with "-v log.txt" it will be recorded to the log file.

**Comment by shivampaw** [comment] 2016-09-10 09:16
Ok I have started it again with the logs and will let you know.

**Comment by shivampaw** [comment] 2016-09-10 09:49
Right so from what I could see.

It failed to recreate the access token and logged out and then that gave it an exception and then started waiting for an account.

**Comment by shivampaw** [comment] 2016-09-10 09:50
Exact exception is

"Exception in search_worker using account xxxxxxx. Restarting with fresh account. See logs for details."

Log error:

"Exception in search_worker under account xxxxxxx Exception message: sequence index must be integer, not 'str'"

**Comment by filippounitn** [comment] 2016-09-11 09:55
same problem here. I don't want to change accounts ... how do i change this "feature" ?
everything goes to sleep after 15 or so minutes, when before this "feature" it was working flawlessly

**Comment by shivampaw** [comment] 2016-09-11 17:00
Reverting to before #996 fixed the problem for me.

**Comment by shivampaw** [comment] 2016-09-17 14:42
Anything done to fix this?

**Comment by FrostTheFox** [comment] 2016-09-18 19:00
I myself am actually getting this issue. I believe there may be a PR to fix this, I'm gonna try to see what the status is on this.

**Comment by jchristi** [comment] 2016-09-20 03:13
@shivampaw Do you have a stacktrace with the error? Is there a line number? This sounds like a pretty easy fix if I knew where the error was.

**Comment by neskk** [comment] 2016-09-25 05:23
If I had to guess this is my problem too and it has to do with an exception arising, either from too many connections to DB or other form of DB locking, causing the worker to be put immediately to "rest" when all it got was a DB exception and should just retry again a few seconds later.

**Comment by shivampaw** [comment] 2016-10-01 22:46
Has it been fixed?

@jchristi I posted everything I could get. Sorry.

**Comment by jchristi** [comment] 2016-10-02 03:57
@shivampaw nothing in #996 stands out to me as a bug like the error you are seeing (`sequence index must be integer, not 'str'`), is there any other code you've merged locally?

**Comment by shivampaw** [comment] 2016-10-02 07:29
No code merged locally. And it might not be 996 but that's what I reverted to because it was working before then. It's something after 996. Initially I thought it was to do with worker switching but I used -asi 0 or something like that to disable it but it still happened.

**Comment by shivampaw** [comment] 2016-10-02 16:48
I have updated to latest and I'm running with this code:
`python runserver.py -ps -fl -ss -nsc -asi 0 -ari 30 -mf 10`

will let you know what happens.

**Comment by shivampaw** [comment] 2016-10-03 06:08
2016-10-02 22:20:19,990 [    Thread-42148][           app][   ERROR] Exception on /loc [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1637, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1837, in preprocess_request
  File "/usr/local/lib/python2.7/site-packages/playhouse/flask_utils.py", line 165, in connect_db
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3404, in connect
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3402, in connect
  File "/usr/local/lib/python2.7/site-packages/playhouse/pool.py", line 128, in _connect
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3929, in _connect
  File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 690, in __init__
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 939, in connect
OperationalError: (2003, "Can't connect to MySQL server on '185.112.249.77' ([Errno 24] Too many open files)")
2016-10-02 22:20:21,171 [    Thread-41388][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 75, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by shivampaw** [comment] 2016-10-03 10:23
Anyone understand this?

**Comment by shivampaw** [comment] 2016-10-03 10:23
@jchristi see above. Thanks

**Comment by jchristi** [comment] 2016-10-03 17:29
That's a network error, 99% sure that is your connection and not the code. Are you using proxies?

**Comment by shivampaw** [comment] 2016-10-03 17:32
Nope.

It was working before the update though?

I'll start running it again and try to catch what exactly happens and where the problem starts. What's the best way to do that?

**Comment by shivampaw** [comment] 2016-10-03 18:05
@jchristi 

I saw a bunch of the accounts getting logged out because of map download failed then there was an exception so I stopped the map to grab the screen at that time.


```

2016-10-03 10:14:55,272 [search-worker-33][      auth_ptc][    INFO] Forced request of PTC Access Token!
2016-10-03 10:14:55,411 [search-worker-63][        search][    INFO] Searching at 52.575061,-1.871421
2016-10-03 10:14:55,419 [ search-worker-5][        search][    INFO] Searching at 52.575061,-1.873209
2016-10-03 10:14:55,605 [ search-worker-5][        search][ WARNING] Exception while downloading map:
2016-10-03 10:14:55,605 [ search-worker-5][        search][   ERROR] Invalid response at 52.575061,-1.873209, abandoning location
2016-10-03 10:14:55,772 [search-worker-33][        pgoapi][   ERROR] Request for new Access Token failed! Logged out...
2016-10-03 10:14:55,773 [search-worker-33][        search][ WARNING] Exception while downloading map: Request for new Access Token failed! Logged out...
2016-10-03 10:14:55,773 [search-worker-33][        search][   ERROR] Invalid response at 52.575061,-1.869633, abandoning location
2016-10-03 10:14:56,090 [search-worker-63][        models][    INFO] Parsing found 0 pokemons, 5 pokestops, and 0 gyms
2016-10-03 10:14:56,127 [search-worker-60][        search][    INFO] Searching at 52.575061,-1.874998
2016-10-03 10:14:56,172 [search-worker-40][        search][    INFO] Searching at 52.575061,-1.876786
2016-10-03 10:14:56,571 [     Thread-2536][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 75, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()   
  File "/usr/local/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
2016-10-03 10:14:56,609 [search-worker-62][        search][    INFO] Searching at 52.576004,-1.877680
2016-10-03 10:14:56,796 [search-worker-40][      auth_ptc][    INFO] Forced request of PTC Access Token!
2016-10-03 10:14:56,923 [search-worker-65][        search][    INFO] Searching at 52.576948,-1.878575
2016-10-03 10:14:57,230 [search-worker-30][        search][    INFO] Searching at 52.577891,-1.879469
2016-10-03 10:14:57,526 [search-worker-36][        search][    INFO] Searching at 52.578835,-1.880363
2016-10-03 10:14:57,678 [search-worker-40][        pgoapi][   ERROR] Request for new Access Token failed! Logged out...
2016-10-03 10:14:57,678 [search-worker-40][        search][ WARNING] Exception while downloading map: Request for new Access Token failed! Logged out...
2016-10-03 10:14:57,678 [search-worker-40][        search][   ERROR] Invalid response at 52.575061,-1.876786, abandoning location
2016-10-03 10:14:57,683 [search-worker-30][        search][ WARNING] Exception while downloading map:
2016-10-03 10:14:57,683 [search-worker-30][        search][   ERROR] Invalid response at 52.577891,-1.879469, abandoning location
2016-10-03 10:14:57,812 [search-worker-62][        models][    INFO] Parsing found 0 pokemons, 6 pokestops, and 2 gyms
2016-10-03 10:14:57,892 [search-worker-65][        models][    INFO] Parsing found 3 pokemons, 5 pokestops, and 2 gyms
2016-10-03 10:14:57,972 [search-worker-44][        search][    INFO] Searching at 52.579778,-1.881257

```

**Comment by shivampaw** [comment] 2016-10-03 18:08
I am now running with this: `python runserver.py -fl -nsc -asi 0 -mf 10`

to see if that helps in any way.

**Comment by shivampaw** [comment] 2016-10-03 18:45
Next update:

I saw it and all the accounts started abandoning because there was an "exception while downloading map"

then they all started cooldowns for 7000 seconds. Is there a way to reduce the cooldown from 2 hours to like 30 seconds?

That might help for now while this is looked into?

**Comment by sebastienvercammen** [comment] 2018-01-25 13:15
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.

**Closed by sebastienvercammen** 2018-01-25 13:15 UTC
