### ISSUE TITLE
Some required arguments aren't really required under certain conditions

### ISSUE THREAD

**Issue by gabrielsoldani** [RocketMap/RocketMap#999] opened 2016-08-26 05:01 UTC
`--no-server` mode doesn't need a Google Maps key, but we require one anyway.
`--only-server` mode doesn't need account data, but we require it anyway.

**Comment by Xcelled** [comment] 2016-08-26 06:02
Imo this is another reason for splitting this project up into sub-commands or sub-programs, such as a webserver, an overseer, and a worker process.

**Comment by arivero** [comment] 2016-11-18 16:38
That is minor bug, not feature request

**Comment by sebastienvercammen** [comment] 2017-02-23 13:12
Closing because the issue is much older than the current codebase. If you feel this functionality should still be changed, please make a new issue, mention me in it (@sebastienvercammen) and we'll get on it.

**Closed by sebastienvercammen** 2017-02-23 13:12 UTC
Labels: feature request
